### ISSUE TITLE
Antistasi dependencies

### ISSUE THREAD

**Issue by IrLED** [A3Antistasi/antistasiofficial#108]
We need to define the list of mods required for Antistasi to run.
I was confused with the discussion at #5 
Requirement of CBA provides enhancements to development, and some of those are already in the code from my previous pull-requests.
If we aim to be dependency-free, we should stick to it, because some dependencies dictate coding styles/approaches. At the moment it's not a big deal to remove CBA from my parts, but in the future it will be good to know the constrains.

**Comment by StefArma** [comment]
Barbolani always wanted Antistasi compatible with several mods but always made it totally mod undependent.

CBA dependency is something I introduced because i couldn't find a solution for TFAR and beeing lazy to add to add it only to server version and keep the github without.

Honestly i don't know if i would have more ppl requesting how to remove dependency or how to sync TFAR, anyway, if someone find a solution for theese radios i'll be happy to remove the dependency. 

Also, when we gonna have a stable version that we'll call "release 1.9" (1.8 was already another not functioning version) that master-branch will be without cba dependency + a small file to integrate it when preparing the mission for multiplayer server where TFAR will be used.

**Comment by FlyingVolvo** [comment]
I talked to Dedmen, one of the main developers of TFAR about this yesterday. We're currently using an ancient version, the one on steam, rather than his stable repo on github. He recognized synchronization is very buggy in general, but was surprised we got it working for short range. I personally do not see CBA as a large barrier to entry to play the mission, especially with it being on the steam workshop. He, Dedmen, did also not give any assurances about synchronization within the module itself in his 1.0 version that is coming Soon™. Since 1.0 of TFAR is coming up, I would take a look at his 1.0 repo to try to make sure the transition from our old version is as smooth as possible on the main server, and no incompatibilities or conflicting code with the Antistasi framework.

**Comment by IrLED** [comment]
So back to original question: dependencies to other mods, especially CBA (that one is my concern). Do we require it or not? That will affect coding approach in the future (neither negative nor positive, just affects). I'd prefer to have it as the only dependency.

**Comment by StefArma** [comment]
Depends IrLED, i heard that CBA helps a lot with the code because of ability to use functions unavailable otherwise. And, to be honest CBA is 2 megabyte superstable and downlodable by steam. 

As people find Antistasi on steam, they can also download CBA.

I don't know how to answer... i only knew that Barbolani wanted this dependency free. 
Personally i wouldn't mind to keep it required.
