### ISSUE TITLE
AI remote control

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#15]
Considering i'd like Antistasi SP (no MP ofcourse) as a "teamplay among yourself".. i was thinking about improving the remote control and make it transfering the leadership.

Now, if you direct control AI, all vital orders such as "hold fire", "move", "watch", "go prone" will be cancelled. Also if someone take fire the direct control is aborted.

To achieve this i'd need a code that:
- transfer leadership to the actual controlled unit (player or AI) 
- tell the previous guy to "Stop"
- add a keybinding to remote control so just selecting one guy and pressing the key is enough to take control.

In this way, you can hit and run, flank, make diversions and use all the smartness you can to prevail against the enemy army. This will give another meaning of HR and, yes, the player can actually fight longer 'cause he'll leave the commander in the back and he'll make advance his pawns.

**Comment by IrLED** [comment]
What should happen when the original player character is down while in process of controlling AI?
idea - when the player is down he gains control of the AI under his command.

**Comment by VenomSnake1985** [comment]
I think when they original player character goes down while controlling ai he should get a countdown timer of about 10-20 seconds before he loses control of the ai.

**Comment by Barbolani77** [comment]
handleDamage EH for player / players has a control to know if the player is controlling AI or its a real AI, or even an AI controlled by a player.

Why?

Because lots of parameters, specially in SP, depend on Stavros, lots of configurations apply only to Stavros (well, the stavros object, or slowHand), not for the whole AI, and variables such as money or others, are setVariabled to the specific object.

So, thats why as soon as the original unit gets damaged, before anything, the control comes back, before aplying any kind of damage, just in case, to avoid real death.

Remember in SP you don't play with ACE, and thats why ACE disables the feature.
