### ISSUE TITLE
QRF Transport Truck despawn if driver is killed

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#150]
When patrolca.sqf is triggered upon capturing enemy place, if they send a troop transport (truck) and the group leader get killed, the whole truck+crew despawn.

This shouldn't happen

**Comment by IrLED** [comment]
>QRF Troop transport (Ural) despawn if leader is killed

Header gives the description of some behavior (actual? expected?)

>Silently lying since before 1.7.17

It's really irrelevant to bug description, doesn't help

Steps to reproduce?
What is actual behavior?
What is expected behavior?

**Comment by StefArma** [comment]
I quickly dropped the post to remind myself, thanks IrLED :)

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/issues/198

**Comment by colmaniac** [comment]
I have tested several times, on choppers, intercepting road blocks always get in coming chopper, I have tried several ways to bring one down to capture, but always ends up despawning after killing all the crew. I managed to bring one down with very little damage, on intercepting it, I killed the co-pilot then pilot, still nothing, I ordered soldiers to my position where they shot at the craft killing the ai still in, then just despawned.  Does this 100% of the time.  Even bringing one down from the air, I can kill all the AI, the craft goes out of control as it would then soon after id disappears leaving the dead crew behind in fid air then all fall to the ground.
This bug came around for me a while after I captured my first base.  When I captured my first base, 2 copters came in, I was able to disable both and both landed, I killed all the crew neither craft despawned, I was able to capture, but never did.

**Comment by colmaniac** [comment]
Update,  after ages of testing all came out the same, however last time I tried, I hit and caused the craft to land, (hit and burst the fuel tank).  All the crew bailed out, I killed all the crew, craft didnt despawn, on checking the craft, only damage was to heavy damaged fuel tank and no fuel.  At this time I guess untill I can retest, all the crew have to bail before you can capture/prevent it from despawning.

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/219
