### ISSUE TITLE
ACE & CBA parameters externally read

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#151]
As we've membership readed externally it would be very cool to have parameters saved on server which can replace the ones hardcoded into the mission

This will help clans to set by default ACE Advanced Medical for istance etc. without hardcoding it in the mission everytime especially considering we're oftenly updating

**Comment by AlexTriada** [comment]
“Help clans to set by default ace ...” - ??? What the problem, describe pls)

**Comment by AlexTriada** [comment]
Not needed thing

**Comment by StefArma** [comment]
Why you say what is needed or not?

basic medical system is a setting within the mission, if i want it for my server i need to edit the mission myself.

Also, could you please make 1 post only with your sentences?

**Comment by AlexTriada** [comment]
basic medical system is a setting within the mission, if i want it for my server i need to edit the mission myself. - set the settings in the confit file, if you don’t know how, I explain

**Comment by StefArma** [comment]
I'm probably bad at expressing myslef in english... 

i want avoid people to edit the mission, instead they can just edit a .txt file. 
So they keep the .pbo as it is, and they can set ace settings externally, exactly how we do with membership

**Comment by AlexTriada** [comment]
You don’t understand again, confit file not in the mission

**Comment by Sparker95** [comment]
Yes if you explain it would be great.

**Comment by Sparker95** [comment]
Do you mean the params class in server.cfg?
Like this one:
`class Missions
{
	class TestMission01 {
	template = MP_Marksmen_01.Altis;
		difficulty = "veteran";
		        class Params
                {
                };
	};
};`

**Comment by AlexTriada** [comment]
Yes I do

**Comment by StefArma** [comment]
Wow i'm terribly sorry i didn't knew that nor i managed to understand you :( 

I need to add this to the guide, thanks a lot!

**Comment by AlexTriada** [comment]
My bat file to start the server:
@echo off
echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo ++++++++ You will need to close this to stop the server restarting: +++++++++++
echo +++++++++++++++++++++++++++++Server #1 Created+++++++++++++++++++++++++++++++++
echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
:RESTART
arma3server_AS_x64.exe -port=2302 -nosound "-profiles=C:\A3DS1ANTISTASI\Profiles" -config=Antistasi.cfg -hugepages -maxMem=16384 -enableHT -loadMissionToMemory -mod="!Workshop\@CBA_A3;!Workshop\@task_force_radio;!Workshop\@ace;!Workshop\@ACE Compat - RHS Armed Forces of the Russian Federation;!Workshop\@ACE Compat - RHS United States Armed Forces;!Workshop\@ACE Compat - RHS- GREF;!Workshop\@RHSAFRF;!Workshop\@RHSUSAF;!Workshop\@RHSGREF"
FOR /F "TOKENS=1* DELIMS= " %%A IN ('DATE/T') DO SET DATE=%%B
FOR /F "TOKENS=*" %%A IN ('TIME/T') DO SET TIME=%%A
ECHO   %TIME%      %DATE%
GOTO RESTART

**Comment by AlexTriada** [comment]
My config file:
//
// server.cfg
//
// comments are written with "//" in front of them.

// NOTE: More parameters and details are available at http://community.bistudio.com/wiki/server.cfg

// STEAM PORTS (not needed anymore, it's +1 +2 to gameport)
// steamPort       = 8766;     // default 8766, needs to be unique if multiple serves on same box
// steamQueryPort  = 27016;    // default 27016, needs to be unique if multiple servers on same box

// GENERAL SETTINGS
hostname       = "Antistasi : Russia #1";    // Name of the server displayed in the public server list
//password     = "ServerPassword";      // Password required to join the server (remove // at start of line to enable)
passwordAdmin  = "*****";       // Password to login as admin. Open the chat and type: #login password
maxPlayers     = 60;    // Maximum amount of players, including headless clients. Anybody who joins the server is considered a player, regardless of their role or team.
persistent     = 1;     // If set to 1, missions will continue to run after all players have disconnected; required if you want to use the -autoInit startup parameter

// VOICE CHAT
disableVoN       = 0;     // If set to 1, voice chat will be disabled
vonCodec = 1;
vonCodecQuality  = 10;    // Supports range 1-30; 1-10 is 8kHz (narrowband), 11-20 is 16kHz (wideband), 21-30 is 32kHz (ultrawideband); higher = better sound quality, more bandwidth consumption

// VOTING
voteMissionPlayers  = 1;       // Minimum number of players required before displaying the mission selection screen, if you have not already selected a mission in this config
voteThreshold       = 0.33;    // Percentage (0.00 to 1.00) of players needed to vote something into effect, for example an admin or a new mission. Set to 9999 to disable voting.
allowedVoteCmds[] =            // Voting commands allowed to players
{
	// {command, preinit, postinit, threshold} - specifying a threshold value will override "voteThreshold" for that command
	{"admin", false, false}, // vote admin
	{"kick", false, true, 0.51}, // vote kick
	{"missions", false, false}, // mission change
	{"mission", false, false}, // mission selection
	{"restart", false, false}, // mission restart
	{"reassign", false, false} // mission restart with roles unassigned
};

// WELCOME MESSAGE ("message of the day")
// It can be several lines, separated by comma
// Empty messages "" will not be displayed, but can be used to increase the delay before other messages
motd[] =
{
	!!!HARDCORE!!!,
	
	Наш сервер тимспика:,
	
	triada.ddns.net,
	
	Наш сервер тимспика:,
	
	triada.ddns.net,
	
	Наш сервер тимспика:,
	
	triada.ddns.net,
	
	Наш сервер тимспика:,
	
	triada.ddns.net,
	
	Наш сервер тимспика:,
	
	triada.ddns.net,
	
	Наш сервер тимспика:,
	
	triada.ddns.net,
	
	Наш сервер тимспика:,
	
	triada.ddns.net,
	
	Наш сервер тимспика:,
	
	triada.ddns.net
};
motdInterval = 5;    // Number of seconds between each message
forcedDifficulty = "Custom";
// MISSIONS CYCLE
class Missions
{
	
	class Antistasi
	{
		template = "Antistasi.Altis";
		difficulty = "Custom"; // "Recruit", "Regular", "Veteran", "Mercenary"
			class Params
			{
				// Настройки миссии
				AS_param_onlyPermanentMembers = 0;
				AS_param_tkPenalty = 1;
				ace_map_BFT_ShowPlayerNames = 0;
				ace_medical_increaseTrainingInLocations = 1;
				ace_microdagr_mapDataAvailable = 1;
				ace_repair_repairDamageThreshold_engineer = 0.5;
				ace_medical_medicSetting_basicEpi = 1;
			};
	};
};

missionWhitelist[] = {Antistasi.Altis};

// LOGGING
timeStampFormat  = "short";                 // Timestamp format used in the server RPT logs. Possible values are "none" (default), "short", "full"
logFile          = "server_console.log";    // Server console output filename

// SECURITY
BattlEye             = 0;    // If set to 1, BattlEye Anti-Cheat will be enabled on the server (default: 1, recommended: 1)
verifySignatures     = 2;    // If set to 2, players with unknown or unsigned mods won't be allowed join (default: 0, recommended: 2)
kickDuplicate        = 0;    // If set to 1, players with an ID that is identical to another player will be kicked (recommended: 1)
allowedFilePatching  = 1;    // Prevents clients with filePatching enabled from joining the server (0 = block filePatching, 1 = allow headless clients, 2 = allow all) (default: 0, recommended: 1)

// FILE EXTENSIONS
allowedLoadFileExtensions[] =       {"hpp","sqs","sqf","fsm","cpp","paa","txt","xml","inc","ext","sqm","ods","fxy","lip","csv","kb","bik","bikb","html","htm","biedi"}; // only allow files with those extensions to be loaded via loadFile command (since Arma 3 v1.19.124216) 
allowedPreprocessFileExtensions[] = {"hpp","sqs","sqf","fsm","cpp","paa","txt","xml","inc","ext","sqm","ods","fxy","lip","csv","kb","bik","bikb","html","htm","biedi"}; // only allow files with those extensions to be loaded via preprocessFile / preprocessFileLineNumbers commands (since Arma 3 v1.19.124323)
allowedHTMLLoadExtensions[] =       {"htm","html","php","xml","txt"}; // only allow files and URLs with those extensions to be loaded via htmlLoad command (since Arma 3 v1.27.126715)

// EVENT SCRIPTS - see http://community.bistudio.com/wiki/ArmA:_Server_Side_Scripting
onUserConnected     = "";    // command to run when a player connects
onUserDisconnected  = "";    // command to run when a player disconnects
doubleIdDetected    = "";    // command to run if a player has the same ID as another player in the server
onUnsignedData      = "kick (_this select 0)";    // command to run if a player has unsigned files
onHackedData        = "kick (_this select 0)";    // command to run if a player has tampered files

// HEADLESS CLIENT
headlessClients[]  = {"127.0.0.1","192.168.88.21"};    // list of IP addresses allowed to connect using headless clients; example: {"127.0.0.1", "192.168.1.100"};
localClient[]      = {"127.0.0.1","192.168.88.250"};    // list of IP addresses to which are granted unlimited bandwidth; example: {"127.0.0.1", "192.168.1.100"};

**Comment by AlexTriada** [comment]
Server.Arma3Profile

version=1;
blood=1;
singleVoice=0;
gamma=1;
brightness=1;
maxSamplesPlayed=96;
class DifficultyPresets
{
	class CustomDifficulty
	{
		class Options
		{
			groupIndicators=0;
			friendlyTags=0;
			enemyTags=0;
			detectedMines=0;
			commands=0;
			waypoints=0;
			weaponInfo=2;
			stanceIndicator=2;
			reducedDamage=0;
			staminaBar=1;
			weaponCrosshair=0;
			visionAid=0;
			squadRadar=0;
			thirdPersonView=1;
			cameraShake=1;
			scoreTable=0;
			deathMessages=1;
			vonID=1;
			autoReport=0;
			multipleSaves=1;
			tacticalPing=0;
			mapContentFriendly=0;
			mapContentEnemy=0;
			mapContentMines=1;
		};
		aiLevelPreset=3;
	};
	class CustomAILevel
	{
		skillAI=1;
		precisionAI=1;
	};
};
activeKeys[]=
{
	"BIS_Antistasi.Altis_done"
};
sceneComplexity=400000;
shadowZDistance=100;
viewDistance=6000;
preferredObjectViewDistance=6000;
terrainGrid=25;
volumeCD=10;
volumeFX=10;
volumeSpeech=10;
volumeVoN=10;
vonRecThreshold=0.029999999;
