### ISSUE TITLE
Problems in antistasi

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/antistasiofficial#152]
Dudes, in antistasi I see only 2 problem - performance and quantity of bots
Performance - HC system is not working now, hc not helping at all, low fps after planes spawning points, low fps with helicopters, low fps with missions
Quantity - very low bots on counterattacks and attack
Not needed - new Arsenal’s, new tablets, new menus, new ... 
Very needed - high fps, working HC, smart bots in high quantity
And fix bugs, pls fix bugs, pls, pls, pls, pls .....

**Comment by StefArma** [comment]
Agree, that's why i posted this project, and are you aware that there is only IrLED that can do such things, i'm still not into coding enough. 
https://github.com/A3Antistasi/antistasiofficial/projects/3

However i'm working on a different checks for QRF, sort of, send QRF when units are killed without any "busy" status or waiting for capture.

https://github.com/A3Antistasi/antistasiofficial/issues/117

**Comment by AlexTriada** [comment]
After this https://github.com/A3Antistasi/antistasiofficial/pull/154 the HC now working!!!
