### ISSUE TITLE
NPC and Players instant dies without option to revive with ACE3.

### ISSUE THREAD

**Issue by angelotadeucci** [A3Antistasi/antistasiofficial#188]
When a NPC or Player gets shot instead of falling on his back, they just die. This is making the mission super extra hard with ACE3. 

Without ACE3 when shot we can revive others like normal.

Is this a bug? Because the parameters looks all right. 
"Ace: Medical level" is on basic.
"Ace: Medical, enable revive?" is on 2.

**Comment by Sparker95** [comment]
There's also an option called 'Prevent instant death' which you should enable.

**Comment by angelotadeucci** [comment]
Sparker95, thanks for answering but where I change this? I'm pretty sure that is not on the parameters. Thanks.

**Comment by StefArma** [comment]
In singleplayer, press escape, settings, you'll see the new addons config added by last CBA and ACE update, there are a lot of configurable parameters. In the medical system there should be one that ask you about AI revive. 

I just warn you that it drain performances especially when AI keep areas spawned in because they're unconscious.

I'd suggest to play singleplayer without the medical system, to do so the safest way is to download ACE from website and remove the folders related to the medical system. 
You keep every nice and useful stuff from ACE but keep the vanilla medical system.

**Comment by angelotadeucci** [comment]
Ah, nice. Thanks.

**Comment by Sparker95** [comment]
Issue closed!
