### ISSUE TITLE
Garrison recruitment blocked - range too high

### ISSUE THREAD

**Issue by CurePindal** [A3Antistasi/antistasiofficial#256]
In a lot of cases the default range value that has to be free of enemies is too high.

Theres too much overlap with defenders of adjacent zones, so you have to clear them out too, just to recruit garrison into a location you captured. So too often you cant recruit garrison or it leads to ugly chain-reactions when you have to clear out other locations, that are very counter-productive for the gameplay. 

In the past 1.5 yrs we came to the conclusion that a range of 100-150m is sufficient and working in almost all areas of Altis.

**Comment by StefArma** [comment]
well QRF actually disembark 400m away... so, i think, barbolani added this limit because of exploit

In any case i dislike the way garrison is added by magical click click... i'd rather prefer garrison is assigned from the units you've under control or at least you send them like you send the truck for a roadblock/camp/watchpost placement 
https://github.com/A3Antistasi/antistasiofficial/projects/3
