### ISSUE TITLE
NATO CAS in enemy territory

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#51]
We disabled the default spawning trigger of NATO aircraft, otherwise every place they move within 1km range would spawn and despawn considering their speed.

This saved a lot of performances, before CAS were avoided to prevent horrible fps drop basically making the feature unavailable.

30 April 2018:
Solution will be: 
- Player jet + all NATO aircraft spawn only AA guys in 4km radius
- Player helicopter spawn units normally + AA guys in 4 km radius 
Wurzel0701 is working on this here: https://github.com/StefArma/antistasiofficial/tree/AirControl

**Comment by vodas3** [comment]
for performance i would recommend not to spawn any units just by the way the aircraft is going calculate chance of falling down and then may be add some missiles or something just for the visual effects (if needed if not too far)

**Comment by StefArma** [comment]
Continue here https://github.com/A3Antistasi/antistasiofficial/pull/134

**Comment by AlexTriada** [comment]
C) - the best, for my opinion

**Comment by ElectroEsper** [comment]
Thinking of something. Maybe having a check every x seconds(server side) when Cas is spawned. Ex.

## AA sites have a logic with AA units synch to it. 

while(_casInTheAir) do {
  _closeAAsite=nearestObjects [_CasVehPos,  "AAsitelogicObjectsClass", 3000, true];
If((count _closeAAsite) > 0) then {spawn AAsites};
  sleep 2;
}

## if more than zero AA site logic is in range while Cas is alive then it would spawn synchronized AA units. (assuming they can be synchronized, haven't checked how you handle troops caching.)
## Do a reverse check to despawn the sites if Cas is dead or left the zone. 

Draft as can be but that's what I could see work maybe. Since I haven't scripted in a while and have no idea how you handle a unit I'm not sure how feasible it is this way tho.

**Comment by Sparker95** [comment]
Another way to do it: put the AA units at the AA site into a different location(marker, or how is it called in antistasi?). Then for this type of markers set different spawn rules: it can be spawned by an aircraft from, say, 5kilometers, OR by standard units from a standard range.

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/322
