### ISSUE TITLE
Adding garrisons soldiers massievly

### ISSUE THREAD

**Issue by 3n1gmaa** [A3Antistasi/antistasiofficial#61]
It would be way better to first choose type of units that you want in garrison and then recruit them other than single clicking on every type of unit. It's sometimes annoying that you can't recruit garrison just because area is too close to HQ or enemies are nearby.

You choose what units you want to recruit ex. "4 Militiamen, 2 Medics, 2 AT, 1 Squadleader" and then hit "Recruit" button. Not sure if that is possible but it could save some time and nerves recruiting garrison.

**Comment by StefArma** [comment]
That word "massively" scary me.

So far, a server + 1 headlessclient connected can handle 180 AI maximum, so consider that i tried to balance most of the AO(assuming you're not going in multiple directions) with an average of 120 units, an attack add other 40 units. 

Let's say you add 10 garrison: that's fine but you're getting close to the limit before performances drop(not specifically FPS, can just be AI combat skill decrease)

It's in long termn priority but garrisoning should be reworked so that you've to send/escort a truck(and maybe even helo) because units appearing from nowhere aren't really in line with the Antistasi project.

That's why there is the nearby unit check, to assure you're adding garrison only where is safe already. 

About the technical GUI thing, that can be infact nice,  you can contribute with the code if you wish :) i've a pretty dense roadmap already.

**Comment by 3n1gmaa** [comment]
Well, maybe I didn't express myself about "massively" clearly enough, it might be just lack of words to describe my thoughts but I think you got my point right. I meant that it would be just easier to choose what type of soldiers do you want and after that actually recruit them. 

Next thing that I got in mind, according to nearby unit check, for example there is one enemy left in 350m radius. Terrain nearby is full of small wooden sheds, some ruined buildings etc.. It sometimes takes ages if you are unlucky to find him. Idea is that last enemy could just surrender if there is enough of player's forces close to him.

I guess that would be easier to achive as I lack coding knowledge and I doubt that I would be able to code that gui thing. Maybe I could ask somebody else.

**Comment by StefArma** [comment]
That's a good one about last enemy surrender, the check could be: territory captured, check within 350m, count enemies, if <2 then enemies setcaptive. 

Or, even better, if <2 then set waypoint on flag, careless, search and destroy.

**Comment by mnarijnm** [comment]
@StefArma I would say, set a value of 90% more friendly in a area of (around 300 and 500 Meter) that they will change on setcaptive. If you got a garrison of 30 men and they fighting 4 men it would make sense that they will surrender because they are with way less people

**Comment by JustSharkbait** [comment]
I think the surrender option is better then the charge in option. Because a lot times the random enemy you can't find but is holding up progess is simply injured and bleeding out.  So it takes even longer to find him. He wld not go careless even if he was told too because he is down.

**Comment by StefArma** [comment]
True! This open to another problem... ACE unconscious AI.. they are going to die in 5 minutes however they keep the place spawned...
