### ISSUE TITLE
Petros death consequences

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#69]
If non-enemies kill Petros 
- he ask to build HQ again
- if he go ACE unconscious you've to wait 5 min, epi not always working.

If enemies kill Petros
- CSAT support reduce, don't understand how, and it's not intended.
- what if commander "none" or afk?

Some unitentified reports says that mission get stuck in map to select a new HQ

**Comment by mnarijnm** [comment]
I will take a look in this tomorrow. About no commander online: That is a tricky one, because normally it will call the commander to place a new location, we can do something like a countdown so the next highest person have to choice a location. (Can we pick the highest ranked person?)

speaking over HQ building. I encounted that a heli attacked petros and i had to rebuild my HQ (was in a mission closeby), but i was able to build it on the same spot. Because the heli was just vanished

**Comment by StefArma** [comment]
Overall fixed for now, the CSAT reducing was fixed already
